#!/bin/bash

# Author: Jonas Hendrikson 2017 (jonas@hendrikson.se)

if (( $# != 1 )); then
  echo "Containername as single argument!"
  echo "Optionally prepended with container host name:"
  echo "  [container-host-name]:container-name"
  echo "No spaces between host and container."
  exit 2
fi

if ! lxc info "$1" >/dev/null 2>&1; then
  echo "Container does not exist!"
  exit 3
fi

# Läs in en array med snapshotnamn. Äldst först.

snaps=( $(lxc info "$1" |
  awk '/\(taken at / {print $4"\t"$5"\t"$1}' |
  sort |
  awk '{print $3}') )

if (( ${#snaps[*]} <= 3 ))
then
  echo "Too few snapshots. Nothing to delete. Bye!"
  exit 1
else
  deleted=0
  for ((i=0; i<$(( ${#snaps[*]}-3 )); i++)); do
    lxc delete "$1"/${snaps[i]}
    (( deleted++ ))
  done
  echo "Deleted ${deleted} snapshots from $1. The 3 most recent remain."
fi

exit 0
